### ISSUE TITLE
How to use GPU / TPU?

### ISSUE THREAD

**Issue by Lennix** [katanaml/llm-mistral-invoice-cpu#1]
Hey,

thanks so much for this project. Really amazing to see whats possible with mistral.

I happen to have a M1 Pro MacBook and was wondering if you could point me in the direction on how to use the GPU or "neural engine" to speed up the process?

Thanks so much

**Comment by abaranovskis-redsamurai** [comment]
hey,

This app is using CTransformers to run LLM model. You can install CTransformers with M1 support: https://github.com/marella/ctransformers#gpu

I'm building now another sample LLM app with LlamaCPP library, instead of CTransformers. LlamaCPP have good support for M1.

Andrej
