### ISSUE TITLE
Faster processing time on CPU.

### ISSUE THREAD

**Issue by AGRocky** [katanaml/llm-mistral-invoice-cpu#13]
Hey Katanaml team, first of greeting to each one of you and highly appreciating your work on the mistral model to run on cpu. However you have said that the processing time on CPU would be much faster in the upcoming days while waiting for the update can you please tell us how it could be optimised for making it run faster on CPUs. If you could reply on this it would be deeply appreciated.
thanks in adavance.

**Comment by abaranovskis-redsamurai** [comment]
Hey,main repo is here: https://github.com/katanaml/sparrow, this is just sample repo.
