### ISSUE TITLE
No of Tokens Exceeding Max Tokens

### ISSUE THREAD

**Issue by Ashwariya2310** [katanaml/llm-mistral-invoice-cpu#5]
Hi,

First of all, thank you for this repo

right now I am trying to use Mistral Q8 on gpu and while running main.py I am getting the following error. I wanted to know how do I decide the optimal. I am attaching the config.yam for reference. Please help
![Uploading Capture.PNG…]()

**Comment by abaranovskis-redsamurai** [comment]
Hey,

This is sample app repo and I don't actively maintain it. Main code is in Sparrow repo - https://github.com/katanaml/sparrow/tree/main/sparrow-ml/lemming I'm using Ollama to run LLM models and it works much better to handle tokes. You can try.
