### ISSUE TITLE
what are the changes required to run with GPU? model type for phi-2.7 model?

### ISSUE THREAD

**Issue by MalleswararaoMaguluri** [katanaml/llm-mistral-invoice-cpu#6]
Hi, please provide the necessary changes if i want to use with GPU in windows. If i want to use phi2-7 model what i have to write in model_type in yml file. Thanks

**Comment by abaranovskis-redsamurai** [comment]
This is only sample app I dont maintain it. Main solution is here, it runs on Ollama - https://github.com/katanaml/sparrow/tree/main
