### ISSUE TITLE
How to speed up the app

### ISSUE THREAD

**Issue by wgong** [katanaml/llm-mistral-invoice-cpu#8]
Your app works well, 
I would like to know how one may speed up the app.  
I asked Bard for the same question, here is its response - https://g.co/gemini/share/caba9f27a56b

Asked Claude 3, got these response:

To improve the performance of CTransformers in Langchain, you can consider the following strategies:

**Use Quantization:** CTransformers supports quantization, which can significantly reduce the model size and improve inference speed. You can enable quantization when loading the model using the quantize parameter in CTransformerModel.
**Optimize CTransformer Configuration:** CTransformer provides various configuration options to optimize performance, such as setting the number of threads, using CPU or GPU, and enabling optimizations like Operator Fusion. You can adjust these settings in the CTransformerModel initialization.
**Batching:** If you're processing multiple inputs at once, you can leverage batching to improve performance. CTransformers supports batched inference, which can be more efficient than processing inputs individually.
**Caching:** If you're performing repetitive computations on the same input, you can cache the results to avoid redundant computations. Langchain provides caching utilities that can be used with CTransformers.
**Model Pruning:** If the model size is too large, you can consider pruning techniques to reduce the number of parameters while maintaining reasonable performance. Langchain doesn't directly support model pruning, but you can use external libraries like Hugging Face Transformers for this purpose.
**Hardware Acceleration:** If you have access to hardware accelerators like GPUs or specialized AI accelerators, you can leverage them to further improve performance. CTransformers supports GPU inference, which can provide significant speedups for certain models and tasks.

It seems that GPU is an easy solution:  https://g.co/gemini/share/fc9472590c4f

What would you recommend? 
Thanks a lot

**Comment by abaranovskis-redsamurai** [comment]
hey, this is only sample app, repo is not really maintained. main app is here: https://github.com/katanaml/sparrow
